### ISSUE TITLE
AttributeError: 'list' object has no attribute 'field'

### ISSUE THREAD

**Issue by gangtao** [huge-success/sanic-openapi#86]
I am glab to see the latest update to version 0.5.0.
I am hitting this issue after upgrade from 0.4.0 to 0.5.0.

> 
>   File "/Users/gtao/Code/Projects/Personal/dataplay3/server/.venv/lib/python3.6/site-packages/sanic_openapi/swagger.py", line 146, in build_spec
>     "schema": serialize_schema(route_spec.produces.field) if route_spec.produces else None,
> AttributeError: 'list' object has no attribute 'field'

seems it is complaining about the list in produces.

I am using something like this:
`@doc.route(
    summary='list all datasets',
    produces=[{"name": str, "id": str, "type": str, "description": str}],
)`
is that a problem?

**Comment by gangtao** [comment]
it might caused by using doc.route, switch to doc.produces solve the problem.

**Comment by chenjr0719** [comment]
I'm going to reopen this issue because `doc.route()` still support `produces` keyword and it should work without any problem.
I think we have to add some docs/examples to explain how to use `produces` and `consumes`(#69) with `doc.route()`.
